FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
COPY . .

# ARG REACT_APP_API_ENDPOINT
# ARG REACT_APP_DB_ENDPOINT
# ENV REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT
# ENV REACT_APP_DB_ENDPOINT=$REACT_APP_DB_ENDPOINT


RUN npm install

EXPOSE 3000

CMD ["npm", "start"]